In [1]:
import numpy as np

In [2]:
s= np.array([[0.02, 0.005, 0],
       [0.005, -0.02, 0.015],
       [0, 0.015, 0.04]])
s

array([[ 0.02 ,  0.005,  0.   ],
       [ 0.005, -0.02 ,  0.015],
       [ 0.   ,  0.015,  0.04 ]])

### Direction cosines

In [3]:
a,b,c=45,90,135
d,e,f=90,0,90
g,h,i=45,90,45

In [4]:
m= np.array([[np.cos(np.pi*a/180),np.cos(np.pi*b/180),np.cos(np.pi*c/180)],[np.cos(np.pi*d/180),np.cos(np.pi*e/180),np.cos(np.pi*f/180)],[np.cos(np.pi*g/180),np.cos(np.pi*h/180),np.cos(np.pi*i/180)]])
m

array([[ 7.07106781e-01,  6.12323400e-17, -7.07106781e-01],
       [ 6.12323400e-17,  1.00000000e+00,  6.12323400e-17],
       [ 7.07106781e-01,  6.12323400e-17,  7.07106781e-01]])

In [5]:
m.T

array([[ 7.07106781e-01,  6.12323400e-17,  7.07106781e-01],
       [ 6.12323400e-17,  1.00000000e+00,  6.12323400e-17],
       [-7.07106781e-01,  6.12323400e-17,  7.07106781e-01]])

In [6]:
s_new=np.dot(m,np.dot(s,m.T))
s_new

array([[ 0.03      , -0.00707107, -0.01      ],
       [-0.00707107, -0.02      ,  0.01414214],
       [-0.01      ,  0.01414214,  0.03      ]])

### Strain Invariants

In [7]:
I1=s[0,0]+s[1,1]+s[2,2]
I1

0.04

In [8]:
I2=s[0,0]*s[1,1]+s[1,1]*s[2,2]+s[2,2]*s[0,0]-s[0,1]**2-s[1,2]**2-s[2,0]**2
I2

-0.0006500000000000001

In [9]:
I3=s[0,0]*s[1,1]*s[2,2]+2*s[0,1]*s[1,2]*s[2,0]-s[0,0]*s[1,2]**2-s[1,1]*s[0,2]**2-s[2,2]*s[0,1]**2      
I3

-2.1500000000000004e-05

### Principal strain

In [10]:
coeff = [1, -I1, I2, -I3]
roots=np.roots(coeff)
print(np.roots(coeff))
roots=np.sort(roots)
roots=roots[::-1]

[-0.02407849  0.04359779  0.0204807 ]


### maximum shear strain

In [11]:
g_13=(roots[0]-roots[2])
g_13

0.06767628008034313

In [12]:
g_12=(roots[0]-roots[1])
g_12

0.02311709364230467

In [13]:
g_23=(roots[1]-roots[2])
g_23

0.04455918643803845

### Normal strain corresponding to maximum shear strain

In [14]:
n_13=(roots[0]+roots[1])/2
n_13

0.03203924441973026

In [15]:
n_12=(roots[1]+roots[2])/2
n_12

-0.001798895620441299

In [16]:
n_23=(roots[0]+roots[2])/2
n_23

0.009759651200711036

### Octahedral stresses

In [17]:
normal_oct=(roots[0]+roots[1]+roots[2])/3
normal_oct

0.01333333333333333

In [18]:
shear_oct=2/3*np.sqrt((roots[0]-roots[1])**2+(roots[1]-roots[2])**2+(roots[0]-roots[2])**2)
shear_oct

0.05617433182117572