In [1]:
import numpy as np

In [3]:
s= np.array([[2.2*10**(-3), 80423*10**(-3),120634.8*10**(-3)],
       [80423*10**(-3), 0.6*10**(-3), 120634.8*10**(-3)],
       [120634.8*10**(-3), 120634.8*10**(-3), -0.2*10**(-3)]])
s

array([[ 2.200000e-03,  8.042300e+01,  1.206348e+02],
       [ 8.042300e+01,  6.000000e-04,  1.206348e+02],
       [ 1.206348e+02,  1.206348e+02, -2.000000e-04]])

In [4]:
a,b,c=0,90,90
d,e,f=90,60,30
g,h,i=90,150,60

In [5]:
m= np.array([[np.cos(np.pi*a/180),np.cos(np.pi*b/180),np.cos(np.pi*c/180)],
             [np.cos(np.pi*d/180),np.cos(np.pi*e/180),np.cos(np.pi*f/180)],
             [np.cos(np.pi*g/180),np.cos(np.pi*h/180),np.cos(np.pi*i/180)]])
m

array([[ 1.00000000e+00,  6.12323400e-17,  6.12323400e-17],
       [ 6.12323400e-17,  5.00000000e-01,  8.66025404e-01],
       [ 6.12323400e-17, -8.66025404e-01,  5.00000000e-01]])

In [6]:
m.T

array([[ 1.00000000e+00,  6.12323400e-17,  6.12323400e-17],
       [ 6.12323400e-17,  5.00000000e-01, -8.66025404e-01],
       [ 6.12323400e-17,  8.66025404e-01,  5.00000000e-01]])

In [7]:
s_new=np.dot(m,np.dot(s,m.T))
s_new

array([[ 2.20000000e-03,  1.44684301e+02, -9.33096105e+00],
       [ 1.44684301e+02,  1.04472801e+02, -6.03177464e+01],
       [-9.33096105e+00, -6.03177464e+01, -1.04472401e+02]])

In [8]:
I1=s[0,0]+s[1,1]+s[2,2]
I1

0.0026

In [9]:
I2=s[0,0]*s[1,1]+s[1,1]*s[2,2]+s[2,2]*s[0,0]-s[0,1]**2-s[1,2]**2-s[2,0]**2
I2

-35573.36887032

In [10]:
I3=s[0,0]*s[1,1]*s[2,2]+2*s[0,1]*s[1,2]*s[2,0]-s[0,0]*s[1,2]**2-s[1,1]*s[0,2]**2-s[2,2]*s[0,1]**2      
I3

2340712.9719297667

In [11]:
coeff = [1, -I1, I2, -I3]
print(np.roots(coeff))

[ 215.49056135 -135.06636135  -80.4216    ]


In [12]:
def eigen(m):
    w,v = np.linalg.eig(m)
    print('eigen values:',w)
    print('eigen vectors:',v)

In [13]:
eigen(s)

eigen values: [ 215.49056135  -80.4216     -135.06636135]
eigen vectors: [[-5.54397458e-01 -7.07109595e-01 -4.38907143e-01]
 [-5.54394460e-01  7.07103968e-01 -4.38919994e-01]
 [-6.20717521e-01  8.44046252e-06  7.84034284e-01]]


In [14]:
s_new

array([[ 2.20000000e-03,  1.44684301e+02, -9.33096105e+00],
       [ 1.44684301e+02,  1.04472801e+02, -6.03177464e+01],
       [-9.33096105e+00, -6.03177464e+01, -1.04472401e+02]])

In [15]:
I1=s_new[0,0]+s_new[1,1]+s_new[2,2]
I1

0.0026000000000436785

In [16]:
I2=s_new[0,0]*s_new[1,1]+s_new[1,1]*s_new[2,2]+s_new[2,2]*s_new[0,0]-s_new[0,1]**2-s_new[1,2]**2-s_new[2,0]**2
I2

-35573.36887032002

In [17]:
I3=s_new[0,0]*s_new[1,1]*s_new[2,2]+2*s_new[0,1]*s_new[1,2]*s_new[2,0]-s_new[0,0]*s_new[1,2]**2-s_new[1,1]*s_new[0,2]**2-s_new[2,2]*s_new[0,1]**2      
I3

2340712.971929768

In [18]:
coeff = [1, -I1, I2, -I3]
roots=np.roots(coeff)
print(np.roots(coeff))

[ 215.49056135 -135.06636135  -80.4216    ]


In [19]:
eigen(s_new)

eigen values: [ 215.49056135  -80.4216     -135.06636135]
eigen vectors: [[-0.55439746 -0.70710959 -0.43890714]
 [-0.81475437  0.35355929  0.45953361]
 [ 0.16976093 -0.61236578  0.77213301]]


In [20]:
roots=np.sort(roots)
roots=roots[::-1]
roots

array([ 215.49056135,  -80.4216    , -135.06636135])

In [21]:
tau_13=(roots[0]-roots[2])/2
tau_13

175.2784613533391

In [22]:
tau_12=(roots[0]-roots[1])/2
tau_12

147.95608067428233

In [23]:
tau_23=(roots[1]-roots[2])/2
tau_23

27.322380679056778

In [24]:
sig_oct=I1/3
sig_oct

0.0008666666666812262

In [25]:
tau_oct=np.sqrt((2*I1**2-6*I2)/9)
tau_oct

153.9986339172599

In [26]:
tau_oct=1/3*np.sqrt((roots[0]-roots[1])**2+(roots[1]-roots[2])**2+(roots[2]-roots[0])**2)
tau_oct

153.9986339172599

In [ ]:
I = np.identity(3, dtype = float)
print("Matrix b : \n", I)

In [ ]:
Z=np.linalg.solve(A,B)