In [1]:
import math
#find the new stress tensor tau
import numpy as np
import numpy
from numpy import linalg
## initialization of variables

tau=np.array([[60, 40, 0],
       [40, -30, 0],
       [0, 0, -20]]) ## some units
print('stress matrix',tau)

stress matrix [[ 60  40   0]
 [ 40 -30   0]
 [  0   0 -20]]


In [2]:
## stress invariants
I1=tau[0,0]+tau[1,1]+tau[2,2]
I2=tau[0,0]*tau[1,1]+tau[1,1]*tau[2,2]+tau[2,2]*tau[0,0]-(tau[0,1]**2+tau[1,2]**2+tau[2,0]**2)
I3=tau[0,0]*tau[1,1]*tau[2,2]+2*tau[0,1]*tau[1,2]*tau[2,0]-(tau[0,0]*tau[1,2]**2+tau[1,1]*tau[2,0]**2+tau[2,2]*tau[0,1]**2)

In [3]:
print(I1,I2,I3)

10 -4000 68000


In [4]:
coeff = [1, -I1, I2, -I3]
print(np.roots(coeff))

[ 75.20797289 -45.20797289 -20.        ]


In [5]:
roots=np.roots(coeff)
roots=np.sort(roots)
sigma=roots[::-1]
sigma

array([ 75.20797289, -20.        , -45.20797289])

In [6]:
tau_13=(sigma[0]-sigma[2])/2
tau_13

60.207972893961575

In [13]:
sigma_max=320
sigma_tresca_given=sigma_max/2
FOS_tresca=sigma_tresca_given/tau_13

In [14]:
FOS_tresca

2.6574553553196747

In [15]:
sigma_von=1/2*((sigma[0]-sigma[1])**2+(sigma[1]-sigma[2])**2+(sigma[2]-sigma[0])**2)
sigma_von_given=sigma_max
FOS_von=sigma_von_given/np.sqrt(sigma_von)

In [16]:
FOS_von

2.9090909090909043

In [19]:
FOS_rankine_tension=sigma_max/sigma[0]
FOS_rankine_tension

4.254868037078719

In [20]:
FOS_rankine_compression=sigma_max/abs(sigma[2])
FOS_rankine_compression

7.078397448843425

4.254868037078719